name: 29-11-24_env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - attrs
  - beautifulsoup4
  - bleach
  - bottleneck
  - certifi
  - cffi
  - charset-normalizer
  - datasets
  - debugpy
  - decorator
  - dill
  - entrypoints
  - exceptiongroup
  - executing
  - filelock
  - freetype
  - frozenlist
  - fsspec
  - h11
  - httpcore
  - httpx>=0.24.0
  - huggingface_hub
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - joblib
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_server
  - ipywidgets
  - jupyterlab_widgets
  - matplotlib-inline
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pyarrow
  - pygments
  - pysocks
  - python=3.12
  - python-dateutil
  - pytorch
  - pyyaml
  - pyzmq
  - regex
  - requests
  - scikit-learn
  - scipy
  - sentence-transformers  # Added
  - faiss                  # Added
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - sympy
  - terminado
  - threadpoolctl
  - tk
  - tokenizers
  - tornado
  - tqdm
  - traitlets
  - transformers
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - wheel
  - yarl
  - zipp
